[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@source=src",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts"
]